exit
ls
cd ~
ls
cd ..
cat /etc/issue
apt-get install vim
apt-get update
apt-get install vim
vim datagen.js
npm install faker
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
ls
cd ~
cd ..
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
vim datagen.js
node datagen.js 
wq
node datagen.js 
:q
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
vim datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
wq
vim node_modules/
vim datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
vim datagen.js 
node datagen.js 
